from __future__ import annotations

import sys
from pathlib import Path
from typing import Any

# Allow importing minidump_parser from the same directory
_tool_dir = str(Path(__file__).parent)
if _tool_dir not in sys.path:
    sys.path.insert(0, _tool_dir)

from langchain_core.tools import tool

from core.models import ToolContext, ToolMetadata


def build_tool(context: ToolContext, metadata: ToolMetadata):
    @tool(metadata.qualified_name, response_format="content_and_artifact")
    def minidump_analyze(
        file_path: str,
        max_stack_frames: int = 64,
        include_all_threads: bool = False,
        scan_crash_dir: bool = False,
        symbol_paths: str = "",
    ) -> tuple[str, dict[str, Any]]:
        """Parse a Windows minidump (.dmp) file and return crash analysis.

        Reads binary .dmp files generated by Unreal Engine crashes,
        extracts exception info, call stacks, loaded modules, and
        thread state for crash investigation. Automatically reads
        CrashContext.runtime-xml for UE's portable call stack.
        When PDB symbols are available, resolves function names.

        Args:
            file_path: Absolute or host-project-relative path to the .dmp
                file. If scan_crash_dir is True, this can be a directory
                path (e.g. "Saved/Crashes") and the most recent .dmp is
                used.
            max_stack_frames: Maximum stack frames per thread (default 64).
            include_all_threads: Include stacks for all threads, not just
                the crashing thread.
            scan_crash_dir: When True and file_path is a directory, find
                and parse the most recent .dmp file in that tree.
            symbol_paths: Semicolon-separated paths to search for .pdb
                symbol files (e.g. engine Binaries dir).
        """
        try:
            from minidump_parser import (
                format_summary,
                parse_minidump,
                to_analysis_dict,
            )
        except ImportError:
            return (
                "The 'minidump' package is not installed. "
                "Run Setup.bat or: pip install \"minidump>=0.0.22\"",
                {"error": "missing_dependency", "package": "minidump"},
            )

        # Resolve path
        p = Path(file_path)
        if not p.is_absolute():
            host_root = context.resolve_scope_root("host_project")
            p = host_root / file_path

        # Directory scan mode
        if scan_crash_dir and p.is_dir():
            dmp_files = sorted(
                p.rglob("*.dmp"),
                key=lambda f: f.stat().st_mtime,
                reverse=True,
            )
            if not dmp_files:
                return (
                    f"No .dmp files found in {file_path}",
                    {"error": "no_dumps_found", "path": str(p)},
                )
            p = dmp_files[0]

        # Validate
        if not p.exists():
            return (
                f"File not found: {file_path}",
                {"error": "file_not_found", "path": str(p)},
            )

        if not p.suffix.lower() == ".dmp":
            return (
                f"Not a minidump file (expected .dmp): {p.name}",
                {"error": "wrong_extension", "path": str(p)},
            )

        # Parse symbol paths
        sym_path_list = [
            s.strip() for s in symbol_paths.split(";") if s.strip()
        ] if symbol_paths else None

        # Parse
        try:
            result = parse_minidump(
                p,
                max_stack_frames=max_stack_frames,
                include_all_threads=include_all_threads,
                symbol_paths=sym_path_list,
            )
        except Exception as e:
            return (
                f"Failed to parse minidump: {e}",
                {"error": "parse_error", "detail": str(e)},
            )

        summary = format_summary(result)
        analysis = to_analysis_dict(result)

        return (summary, analysis)

    return minidump_analyze
