---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	analyze_prompt(analyze_prompt)
	plan_tasks(plan_tasks)
	route_tasks(route_tasks)
	select_next_task(select_next_task)
	mark_task_failed(mark_task_failed)
	collect_task_result(collect_task_result)
	finalize(finalize)
	__end__([<p>__end__</p>]):::last
	__start__ --> analyze_prompt;
	agentswarm__agent-processing-workflow\3arun_agent_processing --> collect_task_result;
	analyze_prompt --> plan_tasks;
	collect_task_result --> select_next_task;
	mark_task_failed --> collect_task_result;
	plan_tasks --> route_tasks;
	route_tasks --> select_next_task;
	select_next_task -.-> agentswarm__agent-processing-workflow\3arun_agent_processing;
	select_next_task -.-> finalize;
	select_next_task -.-> mark_task_failed;
	finalize --> __end__;
	subgraph agentswarm__agent-processing-workflow
	agentswarm__agent-processing-workflow\3arun_agent_processing(run_agent_processing)
	end
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
